### PR TITLE
testing/update osm.json5

### PR DESCRIPTION
**Pull request by sys0pt**
Minecolony townhall testing

### CODE REVIEW

**Comment by SmylerMC** [comment]
Hi @sys0pt , is this a mistake ?

**Comment by sys0pt** [comment]
no, just want to test some world gen stuff with new (custom) structures and buildungs.

**Comment by SmylerMC** [comment]
You just requested to merge your one commit to `osm.json5` into the main branch of the mod 😅 , which would break it. May I suggest working locally or with your own repository for testing? If you only want to make changes to `osm.json5`, you in fact don't even need to work with the sources, you can install a custom `osm.json5` in the `terraplusplus` subdirectory in your `.minecraft` and it should pick it up.

As for what I think you are trying to do, Terraplusplus does not support generating structures with `osm.json5`. If you really want to do that, you will need to implement your own [`DrawFunction`](https://github.com/BuildTheEarth/terraplusplus/blob/master/src/main/java/net/buildtheearth/terraplusplus/dataset/vector/draw/DrawFunction.java) in Java for it to work. There were plans to rework the generation config and I wanted to add support for structure on that occasion (see #43 ), but it looks like neither @DaMatrix nor I have time to work on this anymore so it won't happen any time soon.

**Comment by sys0pt** [comment]
My bad for being a noob. I'd love to join forces and help you out. Got a lot of time and want to make a custom fork-osm.json5, for custom nbt schematic structures. If i can help you in any way, let me know :)
sry for accidentally merging to main

**Comment by SmylerMC** [comment]
No worries, we have all been there! For next time, if you want to open a pull request for something which is a work in progress, you can open it as a draft, that project maintainers know it's not supposed to be ready.

**Comment by sys0pt** [comment]
My goal is:
-generating more osm-geo tags
-making it compatible with other mods, that generate structures
-finishing the Point
-improving osm capabilities as in (#43) "Internal support to generate small structures at the location of Points"

=> osm tags genertating nbt schematics on point, instead of building outline (for large scale population simulation modpack stuff)

**Comment by sys0pt** [comment]
@SmylerMC Not sure why but my repo wont load as active mod with the new draw function. surely im missing out on some details, but idk what exactly.

**Pull request closed without merging**
