### PR TITLE
Dataset optimization

### PR DESCRIPTION
**Pull request by DaMatrix**
This PR optimizes the fetching and parsing of datasets, generation of terrain features based on external datasets, and does some general code cleanup.

- [x] Configurable dataset URLs with seamless fallback
- [x] Optimize generation of OpenStreetMap segment data (roads, streams, buildings)
- [x] Asynchronous prefetching of terrain data (is this even needed? it's unlikely to provide any sort of noticeable boost in most scenarios)
- [x] Persistent terrain data cache
- [x] Better multiresolution support for elevation data (previously incorrectly referred to as "Lidar"?)
- [ ] ~~Improved water data accuracy (will need a lot of custom tools on my end to generate the data, and so may be postponed to a later date)~~ (postponed to a later date)

Needs testing! Jars can be downloaded [from Jenkins](https://jenkins.daporkchop.net/job/BuildTheEarth/job/terraplusplus/job/gotta-go-fast/).

### CODE REVIEW

**Comment by DaMatrix** [comment]
Just waiting for Barteks to add an async terrain gen api at this point.

Fast OpenStreetMap data will probably come in a separate PR, as making the tools for preprocessing it will take quite a while longer.

**Comment by DaMatrix** [comment]
Ready for testing/review.

**Comment by SmylerMC** [comment]
I'm not sure if this is due to the new CubicChunks or Terra++, but the first world gen takes a very long time.
Looks like most of it is spent in `io.github.opencubicchunks.cubicchunks.core.world.SpawnPlaceFinder#bisect(World, BlockPos, BlockPos)`.

**Comment by SmylerMC** [comment]
Gravel is being generated instead of grass.

**Comment by SmylerMC** [comment]
Getting this error quite regularly in the console when stressing the game a bit, looks like Segments are being modified while being sorted in `CachedChunkData`:
```
[16:57:26] [ForkJoinPool.commonPool-worker-2/ERROR] [terra121]: async exception while loading data
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_265]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_265]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:618) ~[?:1.8.0_265]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591) ~[?:1.8.0_265]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_265]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975) [?:1.8.0_265]
	at io.github.terra121.dataset.MultiresDataset$2State.accept(MultiresDataset.java:146) [MultiresDataset$2State.class:?]
	at io.github.terra121.dataset.MultiresDataset$2State.accept(MultiresDataset.java:122) [MultiresDataset$2State.class:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) [?:1.8.0_265]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) [?:1.8.0_265]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_265]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575) [?:1.8.0_265]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:594) [?:1.8.0_265]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:457) [?:1.8.0_265]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_265]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_265]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_265]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_265]
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.ComparableTimSort.mergeLo(ComparableTimSort.java:744) ~[?:1.8.0_265]
	at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:481) ~[?:1.8.0_265]
	at java.util.ComparableTimSort.mergeCollapse(ComparableTimSort.java:406) ~[?:1.8.0_265]
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:213) ~[?:1.8.0_265]
	at java.util.Arrays.sort(Arrays.java:1246) ~[?:1.8.0_265]
	at io.github.terra121.generator.cache.CachedChunkData.<init>(CachedChunkData.java:53) ~[terraplusplus-91c505aacaded217c1372ad3afcaa6c283542633.jar:?]
	at io.github.terra121.generator.cache.ChunkDataLoader.lambda$load$0(ChunkDataLoader.java:130) ~[terraplusplus-91c505aacaded217c1372ad3afcaa6c283542633.jar:?]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616) ~[?:1.8.0_265]
	... 15 more
[16:57:26] [terra++ disk I/O thread/INFO] [terra121]: Cache miss: https://a.tile.openstreetmap.org/18/132796/90188.png
[16:57:26] [terra++ disk I/O thread/INFO] [terra121]: Cache miss: https://b.tile.openstreetmap.org/18/132797/90188.png
[16:57:27] [ForkJoinPool.commonPool-worker-1/ERROR] [terra121]: async exception while loading data
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_265]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_265]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:618) ~[?:1.8.0_265]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591) ~[?:1.8.0_265]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_265]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575) [?:1.8.0_265]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:594) [?:1.8.0_265]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:457) [?:1.8.0_265]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_265]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_265]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_265]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_265]
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.ComparableTimSort.mergeLo(ComparableTimSort.java:744) ~[?:1.8.0_265]
	at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:481) ~[?:1.8.0_265]
	at java.util.ComparableTimSort.mergeForceCollapse(ComparableTimSort.java:422) ~[?:1.8.0_265]
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:222) ~[?:1.8.0_265]
	at java.util.Arrays.sort(Arrays.java:1246) ~[?:1.8.0_265]
	at io.github.terra121.generator.cache.CachedChunkData.<init>(CachedChunkData.java:53) ~[terraplusplus-91c505aacaded217c1372ad3afcaa6c283542633.jar:?]
	at io.github.terra121.generator.cache.ChunkDataLoader.lambda$load$0(ChunkDataLoader.java:130) ~[terraplusplus-91c505aacaded217c1372ad3afcaa6c283542633.jar:?]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616) ~[?:1.8.0_265]
	... 9 more
```

**Comment by DaMatrix** [comment]
> Gravel is being generated instead of grass.

good catch, almost forgot about that :P

> Getting this error quite regularly in the console when stressing the game a bit, [snip]

huh, not sure what would be causing that... i'm going to be pushing some changes that should completely revamp how OSM data is loaded, so i'll have a look into that once i finish up.

**Comment by DaMatrix** [comment]
both of those things should work now.

**Comment by SmylerMC** [comment]
I can confirm that I was not able to reproduce those errors with those fixes.

**Comment by SmylerMC** [comment]
About the HTTP client, is it really  good idea to have this ?
```
static {
        try {
            SSL_CONTEXT = SslContextBuilder.forClient()
                    .ciphers(Http2SecurityUtil.CIPHERS, SupportedCipherSuiteFilter.INSTANCE)
                    .trustManager(InsecureTrustManagerFactory.INSTANCE)
                    .build();
        } catch (SSLException e) {
            throw new RuntimeException("unable to create ssl context", e);
        }
    }
```
In one hand it's pretty useful to deal with Mojang not shipping the Let's Encrypt CA certificate with the vanilla launcher's JVM, but that seams a bit radical.
If that was to be kept then the Let'sEncyptCraft implementation should be removed from the mod since it would become irrelevant. But I still think the best thing to do would be to have a trust manager that actually checks certificates and add the Let'sEncryt CA cert to it.

I also find the default cache expiration time of one day to be quite low, most OSM service providers require a cache TTL of at least a week if the Cache-Control header is not supported.

**Comment by SmylerMC** [comment]
Is the mod intended to be usable to work with older versions of CC ?
Looks like it is checking if async terrain gen is supported in `EarthGenerator.java`, but the catch block should handle more exceptions: 
```
io.github.terra121.EarthWorldType@31634ec
[00:46:48] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.AttachCapabilitiesEvent@5af14c1f:
java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: io/github/opencubicchunks/cubicchunks/api/worldgen/LoadingData
	at io.github.terra121.generator.EarthGenerator.<clinit>(EarthGenerator.java:67) ~[EarthGenerator.class:?]
	at io.github.terra121.EarthWorldType.createCubeGenerator(EarthWorldType.java:32) ~[EarthWorldType.class:?]
	at net.minecraft.world.WorldProvider.createCubeGenerator(WorldProvider.java:759) ~[aym.class:?]
	at net.minecraft.world.WorldServer.initCubicWorldServer(WorldServer.java:1549) ~[oo.class:?]
	at io.github.opencubicchunks.cubicchunks.core.CommonEventHandler.onWorldAttachCapabilities(CommonEventHandler.java:121) ~[CommonEventHandler.class:?]
	at
....
```

**Comment by DaMatrix** [comment]
> If that was to be kept then the Let'sEncyptCraft implementation should be removed from the mod since it would become irrelevant. But I still think the best thing to do would be to have a trust manager that actually checks certificates and add the Let'sEncryt CA cert to it.

good point, added to my todo list.

> I also find the default cache expiration time of one day to be quite low, most OSM service providers require a cache TTL of at least a week if the Cache-Control header is not supported.

yeah, i guess that should be changed - although note that there won't be a dependency on Overpass once fast-osm is merged. maybe i'll make it configurable per-url like i did with the maximum concurrent connections, and have the `Cache-Control` headers override it.

> Is the mod intended to be usable to work with older versions of CC ?

should be fixed as of dacd2cc0deb657357a5d42b336d7c15831aac892

**Pull request merged**
