### PR TITLE
Ignorecase on Telport Command

### PR DESCRIPTION
**Pull request by Georg-code**
I am on holiday, which is why I cannot check my changes. But I have heard that it bothers some that /tpll is case sensetive. I figured it would be easy to just make the input lowercase. If that doesn't work I apologise and would be happy if someone else could fix it. 
Kind regards

### CODE REVIEW

**Comment by SmylerMC** [comment]
Hello, which text are we talking about here ? Can you provide an example of a text that should work and doesn't ?

**Review by SmylerMC — CHANGES_REQUESTED** [review]
Thanks for your contribution, but this doesn't change the tpll command syntax at all, it just forces the permission node for all commands to be lowercase (which they already are). It also doesn't compile, you'd want to do
```java
this.getName().toLowerCase()
```
instead of
```java
this.toLowerCase().getName()
```
to indeed change the case of the permission node.

**Comment by Georg-code** [comment]
Oops Sorry Embarrassing - The /tpll command must be lowercase at the moment. So /Tpll would not work. I wanted to change that. I didn't have time to look over all the code :/

**Comment by SmylerMC** [comment]
Minecraft command names are expected to be case sensitive, we could probably figure out a way to do what you want but I'm not really a fan of the idea. What's your opinion on this @noahhusby ?

**Comment by Georg-code** [comment]
For servers it is common that it is not case sensitive (In Plugins) => cmd.equalsIgnoreCase(command) 
That commands are not case sensitive if they are not vanilla commands is an unwritten convention. The modpack is used on many servers, so it would be nice if it were no longer case sensitive.

**Pull request closed without merging**
